#ifndef CONST_H_INCLUDED
#define CONST_H_INCLUDED

#define TAILLEX 16
#define TAILLEY 12
#define TAILLECASE 64

#define LARGEUR TAILLECASE * TAILLEX
#define HAUTEUR TAILLECASE * TAILLEY


#define TAILLE_SNAKE_MAX 999

#endif // CONST_H_INCLUDED
